# Generated by Django 3.2.25 on 2026-01-04 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DieselLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('YARDA', 'Yarda'), ('OBRA', 'Obra'), ('DIAM', 'Diam')], max_length=20)),
                ('unidad', models.CharField(max_length=50)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operador', models.CharField(max_length=100)),
                ('precio_por_litro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
