# Generated by Django 3.2.25 on 2026-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diesel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesellog',
            name='precio_por_litro',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
